---
fedora_packages:
  # sway
  - "sway"                          # wayland window manager
  - "swaylock"                      # wayland screen locker
  - "swayidle"                      # wayland idle daemon
  - "mako"                          # wayland notification daemon
  - "waybar"                        # wayland status bar
  - "fuzzel"                        # wayland app launcher
  - "polkit"                        # authorization framework (required to launch sway)
  - "alacritty"                     # terminal emulator
  - "greetd"                        # generic greater daemon
  - "wl-clipboard"                  # wayland clipboard utility
  - "wlsunset"                      # wayland display colour temperature utility

  # cli utilities
  - "vim"                           # text editor
  - "git"                           # version control system
  - "wget"                          # command line utility for retrieving files over HTTP/FTP
  - "curl"                          # command line utility for retrieving files over HTTP/FTP
  - "traceroute"                    # traceroute
  - "mlocate"                       # file finder
  - "p7zip"                         # 7zip
  - "tar"                           # tar
  - "rsync"                         # file synchronization utility
  - "wireguard-tools"               # wireguard vpn
  - "usbutils"                      # usb utilities
  - "cifs-utils"                    # smb/cifs mounting utilities
  - "bind-utils"                    # dig/dns querying utilities
  - "python3"                       # python
  - "python3-pip"                   # python package manager
  - "python3-virtualenv"            # virtualenv for python

  # sound server
  - "pipewire"                      # sound server
  - "pipewire-pulseaudio"           # pipewire pulseaudio implementation
  - "pulseaudio-utils"              # pulseaudio command line utilities
  - "playerctl"                     # command line media player controller
  - "pavucontrol"                   # pulseaudio gui volume control
  - "easyeffects"                   # pipewire gui equalizer

  # themes and fonts
  - "gnome-themes-extra"            # gnome themes including adwaita-dark 
  - "adwaita-qt5"                   # adwaita for qt
  - "qt5ct"                         # qt theme configuration utility
  - "google-noto-emoji-color-fonts" # noto emoji fonts
  - "google-noto-fonts-common"      # noto common fonts
  - "google-noto-sans-mono-fonts"   # noto mono fonts

  # gui applications
  - "Thunar"                        # thunar file manager
  - "thunar-volman"                 # thunar drive automount
  - "thunar-archive-plugin"         # thunar archive manager plugin
  - "gvfs-fuse"                     # virtual filesystem
  - "gvfs-smb"                      # smb support for gvfs
  - "gvfs-mtp"                      # mtp/phone support for gvfs

  - "firefox-wayland"               # web browser
  - "@virtualization"               # qemu/kvm virtual machines
  - "flatpak"                       # alternative package manager
  - "gnome-keyring"                 # framework for managing password and secrets
  - "seahorse"                      # gui secrets manager
  - "evolution"                     # email client
  - "openh264"                      # h.264/mpeg-4 avc
  - "keepassxc"                     # password manager
  - "libreoffice"                   # office software
  - "gimp"                          # photo editor
  - "Zim"                           # desktop wiki/notes
  - "gtkspell3"                     # Zim spell check plugin dependency
  - "python3-sphinx"                # Zim spell check plugin dependency
  - "python3-enchant"               # Zim spell check plugin dependency
  - "gtksourceview3"                # Zim source view plugin dependency
  - "wireshark"                     # packet sniffer
  - "qalculate-gtk"                 # calculator
  #- flameshot                      # screenshot utility doesnt work under wayland
  - "grimshot"                      # screenshot utility
  - "quiterss"                      # RSS reader
  - "evince"                        # document viewer (pdf)
  - "ristretto"                     # photo viewer (also enables thunar image file previews)
  - "nextcloud-client"              # nextcloud
  - "lxpolkit"                      # gui polkit agent
  - "openssh-askpass"               # prompt when using ssh-agent keys
  - "python3-beautifulsoup4"        # waybar-weather.py dependency
